Arrays
arzamaskov/study pull request #1
Opened 2021-12-14 11:18 UTC by arzamaskov

Добавлено решение для arrays

2021-12-17 12:44 UTC, NickelGit requested changes

2021-12-17 12:44 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        max = array.reduce { |larger, item| item > larger ? item : larger }
Вынеси пожалуйста функцию поиска максимума в отдельный метод.

2021-12-17 12:44 UTC, NickelGit commented on test/exercise/arrays/solution.rb
> +        end
Давай вместо slice добавим в аргументы границы поиска, и будем соответственно передавать сам массив, значение которое мы ищем, левую границу поиска и правую границу поиска.
И заменим `if-else` на тернарную операцию.

2021-12-17 14:02 UTC, arzamaskov commented on test/exercise/arrays/solution.rb
> +        end
Немного непонятно, в функции search - изначально только два параметра, т.е. нужно будет добавить еще два параметра - левую и правую границы?

2021-12-21 07:41 UTC, aarzamaskov commented on test/exercise/arrays/solution.rb
> +        end
Переделал с использованием лямбда-фукнции, массив и искомое значение передавать в лямбду не стал, т.к. использую замыкания

2021-12-21 07:41 UTC, aarzamaskov commented on test/exercise/arrays/solution.rb
> +        max = array.reduce { |larger, item| item > larger ? item : larger }
Fixed

2021-12-21 09:08 UTC, NickelGit approved these changes

2021-12-21 10:17 UTC, merged