Add Fp solution
arzamaskov/study pull request #2
Opened 2021-12-24 07:46 UTC by arzamaskov

2022-01-10 11:43 UTC, moklidia requested changes

2022-01-10 11:43 UTC, moklidia commented on test/exercise/fp/solution.rb
> +        films = get_films_by_country(films)
В функциональном программировании нельзя переопределять переменные

2022-02-04 06:50 UTC, arzamaskov commented on test/exercise/fp/solution.rb
> +        films = get_films_by_country(films)
fixed

2022-02-04 13:04 UTC, moklidia requested changes

2022-02-04 13:04 UTC, moklidia commented on test/exercise/fp/solution.rb
> +        films = get_films_by_country(get_films_by_rating(array))
Вложенный вызов функции тяжело читать.

2022-02-04 13:04 UTC, moklidia commented on test/exercise/fp/solution.rb
> +        film_names = films.select { |film| film if film['rating_kinopoisk'].to_f >= threshold }
Внутри селекта не должно быть if

2022-10-02 08:45 UTC, YJorge commented on test/exercise/fp/solution.rb
> +      def validate(film)
название немного странное. По названию метод проводит валидацию и было бы логично, если бы он выдавал результат валидации. Тут же больше подходит fileter  или что-то подобное

2022-10-02 11:01 UTC, arzamaskov commented on test/exercise/fp/solution.rb
> +      def validate(film)
точно, спасибо) исправил

2022-10-02 11:05 UTC, YJorge approved these changes

2022-10-02 11:52 UTC, merged